### ISSUE TITLE
API Docs link in Readme goes to empty directory

### ISSUE THREAD

**Issue by SMSMichael** [coldbox-modules/cbstreams#1]
The API docs link in the readme (https://apidocs.ortussolutions.com/coldbox-modules/cbstreams/index.html) goes to an empty directory listing with no content

**Comment by tcolepc** [comment]
> The API docs link in the readme (https://apidocs.ortussolutions.com/coldbox-modules/cbstreams/index.html) goes to an empty directory listing with no content

I found this direct link

https://apidocs.ortussolutions.com/coldbox-modules/cbstreams/1.4.0/index.html

**Comment by SMSMichael** [comment]
@lmajano any objection to replacing the generic link included above with the direct link to the 1.4 docs that @tcolepc found?  I'm happy to put in a PR with the change if you think that's appropriate.

**Comment by lmajano** [comment]
Yes please, not sure what happened : @SMSMichael

**Comment by lmajano** [comment]
this is now using the `current` slug so it always goes to the latest version
