### ISSUE TITLE
Cannot remove .NFS File: Device or resource busy

### ISSUE THREAD

**Issue by tcolepc** [coldbox-modules/cbstreams#4]
When i use this code on my local machine it works fine. The file is deleted without problems.

        my_stream = my_streamBuilder.new().ofFile( my_file );
        try{
          my_stream
          .foreach( function( item ) {
            dump( item )
          })
        } finally{
          my_stream.close();
        }
        FileDelete( my_file );

But when i try do the same in a Network File System (NFS),  the file is renamed by another one ".nfsXXXXXXXX"

ls -a 
.nfs000000000015f07700000039  
.nfs000000000015f07c0000003c 

rm .nfs000000000015f07500000038
m: cannot remove '.nfs000000000015f07500000038': Device or resource busy

When restart tomcat the files disappear

**Comment by lmajano** [comment]
might be an NFS issue, is this windows?

**Comment by tcolepc** [comment]
Client and server are Ubuntu. The NFS version 3.

We use filedelete often and files are deleted correctly

**Comment by lmajano** [comment]
I am not sure how to even replicate that @tcolepc
