### ISSUE TITLE
component [cbstreams.models.StreamBuilder] has no function with name [ofFile]

### ISSUE THREAD

**Issue by Daemach** [coldbox-modules/cbstreams#6]
The examples show this method to stream process a file.  It's not clear why every stream requires 2 calls, one to `stream` and a second to `streamBuilder` with nearly the same arguments.

```
stream = stream().ofFile( absolutePath );
stream = streamBuilder.new().ofFile( absolutePath );
try{
    work on the stream and close it in the finally block;
} finally{
    stream.close();
}
```

**Comment by lmajano** [comment]
The issue is that we have to build an empty stream first and then tell it to build it of the file.  Mostly because I can't add static methods yet because we need to support adobe 2018.  Once that's not supported, the API will be cleaner
